# Image officielle Microsoft avec le SDK .NET 8 (ou 9 selon tes besoins)
FROM mcr.microsoft.com/devcontainers/dotnet:8.0

# [Optionnel] Installer des outils supplémentaires comme 'curl' ou 'git' 
# si l'image de base ne les a pas (mais ici ils y sont déjà)
