// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTracker.Infrastructure.Persistence;

#nullable disable

namespace MyTracker.Infrastructure.Migrations
{
    [DbContext(typeof(TrainingTrackerDbContext))]
    [Migration("20260626154524_AddFtpVmaCssToUserProfile")]
    partial class AddFtpVmaCssToUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MyTracker.Infrastructure.Persistence.Entities.ActivityCommentaryEntity", b =>
                {
                    b.Property<string>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId");

                    b.ToTable("ActivityCommentaries");
                });

            modelBuilder.Entity("MyTracker.Infrastructure.Persistence.Entities.ActivityDataPointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Cadence")
                        .HasColumnType("REAL");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<double?>("Grade")
                        .HasColumnType("REAL");

                    b.Property<double?>("HeartRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double?>("Lng")
                        .HasColumnType("REAL");

                    b.Property<bool?>("Moving")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<int>("TimeOffset")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Velocity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Watts")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "TimeOffset")
                        .IsUnique();

                    b.ToTable("ActivityDataPoints");
                });

            modelBuilder.Entity("MyTracker.Infrastructure.Persistence.Entities.ActivityEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageWatts")
                        .HasColumnType("REAL");

                    b.Property<double?>("Calories")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<double>("ElevationGain")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("EndLng")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsFullyImported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapPolyline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxHeartRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxWatts")
                        .HasColumnType("REAL");

                    b.Property<int>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<double?>("StartLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartLng")
                        .HasColumnType("REAL");

                    b.Property<double?>("SufferScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("MyTracker.Infrastructure.Persistence.Entities.ActivityLapEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ElevationGain")
                        .HasColumnType("REAL");

                    b.Property<int>("LapIndex")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxHeartRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<int>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("StravaLapId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "LapIndex")
                        .IsUnique();

                    b.ToTable("ActivityLaps");
                });

            modelBuilder.Entity("MyTracker.Infrastructure.Persistence.Entities.ActivitySplitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ElevationDifference")
                        .HasColumnType("REAL");

                    b.Property<int>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaceZone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SplitIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "SplitIndex")
                        .IsUnique();

                    b.ToTable("ActivitySplits");
                });

            modelBuilder.Entity("MyTracker.Infrastructure.Persistence.Entities.UserProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CriticalSwimSpeedMinPer100m")
                        .HasColumnType("REAL");

                    b.Property<double?>("FtpWatts")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightCm")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestingHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("VmaMinPerKm")
                        .HasColumnType("REAL");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
