// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTracker.Infrastructure.Persistence;

#nullable disable

namespace MyTracker.Infrastructure.Migrations
{
    [DbContext(typeof(TrainingTrackerDbContext))]
    [Migration("20260625194718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MyTracker.Infrastructure.Persistence.Entities.ActivityCommentaryEntity", b =>
                {
                    b.Property<string>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId");

                    b.ToTable("ActivityCommentaries");
                });

            modelBuilder.Entity("MyTracker.Infrastructure.Persistence.Entities.ActivityDataPointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Cadence")
                        .HasColumnType("REAL");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL");

                    b.Property<double?>("Grade")
                        .HasColumnType("REAL");

                    b.Property<double?>("HeartRate")
                        .HasColumnType("REAL");

                    b.Property<int>("TimeOffset")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Velocity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Watts")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "TimeOffset")
                        .IsUnique();

                    b.ToTable("ActivityDataPoints");
                });

            modelBuilder.Entity("MyTracker.Infrastructure.Persistence.Entities.ActivityEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageWatts")
                        .HasColumnType("REAL");

                    b.Property<double?>("Calories")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<double>("ElevationGain")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxHeartRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxWatts")
                        .HasColumnType("REAL");

                    b.Property<int>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SufferScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
